USE [master]
GO
CREATE DATABASE [ArabaAl]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ArabaAl', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ArabaAl.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ArabaAl_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ArabaAl_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ArabaAl] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ArabaAl].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ArabaAl] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ArabaAl] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ArabaAl] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ArabaAl] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ArabaAl] SET ARITHABORT OFF 
GO
ALTER DATABASE [ArabaAl] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ArabaAl] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ArabaAl] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ArabaAl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ArabaAl] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ArabaAl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ArabaAl] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ArabaAl] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ArabaAl] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ArabaAl] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ArabaAl] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ArabaAl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ArabaAl] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ArabaAl] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ArabaAl] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ArabaAl] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ArabaAl] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ArabaAl] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ArabaAl] SET  MULTI_USER 
GO
ALTER DATABASE [ArabaAl] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ArabaAl] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ArabaAl] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ArabaAl] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ArabaAl] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ArabaAl] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ArabaAl] SET QUERY_STORE = OFF
GO
USE [ArabaAl]
GO
/****** Object:  Table [dbo].[tblArabaBilgi]    Script Date: 15.05.2023 15:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblArabaBilgi](
	[arabaID] [int] IDENTITY(1,1) NOT NULL,
	[arabaModel] [nvarchar](50) NOT NULL,
	[arabaMarkasiID] [int] NOT NULL,
	[arabaYakitTipi] [nvarchar](50) NULL,
	[arabaAciklamasi] [nvarchar](max) NULL,
	[arabaIletisim] [nvarchar](50) NOT NULL,
	[arabaSaticisi] [nvarchar](100) NULL,
	[arabaResim] [nvarchar](max) NULL,
	[arabaFiyati] [int] NOT NULL,
	[arabaOnay] [bit] NOT NULL,
 CONSTRAINT [PK_tblArabaBilgi] PRIMARY KEY CLUSTERED 
(
	[arabaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblIletisim]    Script Date: 15.05.2023 15:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblIletisim](
	[iletisimID] [int] IDENTITY(1,1) NOT NULL,
	[mesaj] [nvarchar](max) NOT NULL,
	[mail] [nvarchar](50) NOT NULL,
	[isim] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_tblIletisim] PRIMARY KEY CLUSTERED 
(
	[iletisimID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblMarka]    Script Date: 15.05.2023 15:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblMarka](
	[markaID] [int] IDENTITY(1,1) NOT NULL,
	[markaAdi] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_tblMarka] PRIMARY KEY CLUSTERED 
(
	[markaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblUyeler]    Script Date: 15.05.2023 15:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUyeler](
	[uyeID] [int] IDENTITY(1,1) NOT NULL,
	[uyeMail] [nvarchar](50) NOT NULL,
	[uyeParola] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_tblUyeler] PRIMARY KEY CLUSTERED 
(
	[uyeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblArabaBilgi] ADD  CONSTRAINT [DF_tblArabaBilgi_arabaOnay]  DEFAULT ((0)) FOR [arabaOnay]
GO
ALTER TABLE [dbo].[tblArabaBilgi]  WITH CHECK ADD  CONSTRAINT [FK_tblArabaBilgi_tblMarka] FOREIGN KEY([arabaMarkasiID])
REFERENCES [dbo].[tblMarka] ([markaID])
GO
ALTER TABLE [dbo].[tblArabaBilgi] CHECK CONSTRAINT [FK_tblArabaBilgi_tblMarka]
GO
USE [master]
GO
ALTER DATABASE [ArabaAl] SET  READ_WRITE 
GO
